packages:
  - 'packages/framework/block-std'
  - 'packages/framework/global'
  - 'packages/framework/inline'
  - 'packages/framework/store'
  - 'packages/framework/sync'
  - 'packages/framework/react'
  - 'packages/blocks'
  - 'packages/docs'
  - 'packages/playground'
  - 'packages/presets'
  - 'examples/react-custom'
